# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NateIndie - Strive Blog
email: nateindie@yahoo.com
description: New Zealand indie developer
twitter_username: nateindie
github_username:  nateindie
baseurl: "Strive"

# Build settings
markdown: kramdown
